### ISSUE TITLE
News after having been removed from core

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-visual-script#32]
Hi,

I have several small pro titles in work, and, I use visual script . . It was getting very good, for small team, perhaps a medium studio even, etc . . Is there any time frame, since it's bit annoying for pro teams to suddenly lose a almost productivity feature . . Not to put pressure, just to get some overview . .

Last, here are some more for debate, if it fits here, some important topics . .

1. Godot visual script is full coding system, keep it that way, makes it useful also for professional work . .
2. The current UI is very good, in almost every way
3. A wish feature is a better ' hint ' feature, where one could click a ' ? ' setting, when hovering over boxes, they give info over what ports do, so, there's an inbuilt docus setting, and, less need for user - tutorials . . Hover over port, in ' ? ' mode, one gets a hint, how it works, this could take ton of time, and, not really sure . . .
4. Basically, Godot 4 visual script is already a win, for single person, small team, perhaps even a medium size studio, so, I hope the feature will get more attention, it's also amazing for beginners, that want to learn how Godot works, simple code, and, yea, finally so good it's useful to small, I'd say also medium sized teams, 40 - 50 people . .

Was sort-of annoyed to see visual script removed, when it was finally getting as good, as rest of engine, sort-of almost as good, as even C # . . . As someone who has some titles for Godot, and where this is a serious productivity issue, very keen to hear any news, and, one last time, give this feature a little praise, and, also how the years of work put into the feature, is really starting to show, #thx . . . :-)

**Comment by charlesmlamb** [comment]
Atm, working on a sci-fi card game, has perhaps speed-chess, could code this in visual script, in a few weeks, to learn gdscript, it'd take me prob. six months, instead, that's why I'm slightly concerned, also worried, that this feature has been removed, and, hope there's a future, esp. because it also got very, very good, in Godot 4, UI, everything, really nice coding system, advanced, a place for beginners, also, semi - pro studios, removing it has set me back about six months, lol . . . :-O 

![image](https://user-images.githubusercontent.com/83387915/188914970-c3f74d9c-fa99-4288-9dfb-93fc761f2182.png)

So, any news for someone looking to make some almost pro work, it'd be quite important, using another engine that has visual script is sort-of a time - saver, however, keeping these ideas for Godot, when visual script can be an easy-to-install add-on, #thx . . . .

**Comment by charlesmlamb** [comment]
Any news, could one soon get visual script for Godot 4, or is it going to take say six months, a year, #thx . . .

**Comment by fire** [comment]
Hey @charlesmlamb,

Thanks for your thoughts! Your report isn't exactly a bug, but more of a feature request and feedback about Godot's visual script system. We get why you're worried about the removal of the visual script in Godot 4. It was a tough call, but we made it based on user feedback, usage stats, and our roadmap.

Your ideas to improve the 'hint' feature and keep the current UI are great. Could you submit them as feature requests? That way, others can chime in and vote on them.

We love your passion for Godot and can't wait to see what you'll bring to our community.
