### ISSUE TITLE
There are some issues in compiling Godot 4 beta4 with Visual-Script.

### ISSUE THREAD

**Issue by kitsdream** [godotengine/godot-visual-script#50]
There are some issues in compiling Godot 4 beta4 when I put Visual-Script in it , and I had changed SCsub's line 10 to 'If env.editor_build:', but I still got this below...Could you please update Visual-Script to make it compatible？
![屏幕截图_20221124_173511](https://user-images.githubusercontent.com/79633060/203753046-0a2d0f09-98ca-4b7c-9477-1ed1910c352c.png)

**Comment by fire** [comment]
There are bugs but Visual Script should compile on Godot Engine master now. 

https://github.com/godotengine/godot/commit/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe
