### ISSUE TITLE
List of common possible blocks/behaviours to have as high level blocks (reference issue).

### ISSUE THREAD

**Issue by ca3gamedev** [godotengine/godot-visual-script#51]
I will try to compile here a list of possible high level behaviours that are so common in videogames, It would make sense to have somehow as big visual blocks.

Like walk, run, do punch. 2 directional walk, 4 directional tile walk, 8 directional free movement, dash when pressing a button and using stamina, using stamina for movement, create a npc jrpg like message, save file. increase HP, decrease HP. change GUI variable. make light or sun rotate in the scene. move and tween camera. make a character jump. Move a platform between two points. react to character being punched/attacked with melee. basic list of attacking states, also reacting to damage states, win, KO, die, taunt/dancing/dab state, basic emotional trigger animations, for jrpg cutscenes, like angry, happy, excited, loved, scared, sad, depressed. do some fighting game input. scene transition, call a certain sound, music, animation. play a random music loop from a list. play cutscene. enter timer. open an inventory. throw fireball. fireball moving as a level trap or enemy spell. touhou bullet patterns. climb a ladder/wall, kick a ball, select RTS units using the mouse. Drag an item, Carry an item. Aim like an FPS.  swim, drop loot. throw a pokeball/item.  change a weapon/model/hat/shield. Maybe give commands to pets/pokemons like a real time action jrpg party. Show a GUI screen, hide a GUI element, change a GUI widget. turn on a flashlight, turn off. Camera following something.  Show a texture on snow footsteps, damage to model from being shot, or wear and tear. Open a lock/safe. JRPG style message. Time over Message from fighting games. Go here message from beatem ups. Switch object with a damaged version. Weather animations like snow, rain, sunny day lenses post processing templates. Particles for fire, lava, explosion, candy/confetti. Drive a vehicle (vehicle character controller). Bouncing/Mirroring a tennis/pong ball.

that's pretty much everything I can thing off.
This is just a basic reference list I made, I wanted to share.

**Comment by fire** [comment]
Here is your list of high-level behaviors common in video games, formatted as a table by gpt4:

| Category | Behaviors |
| --- | --- |
| **Movement** | Walk, Run, 2 directional walk, 4 directional tile walk, 8 directional free movement, Dash when pressing a button and using stamina, Using stamina for movement, Climb a ladder/wall, Swim, Drive a vehicle (vehicle character controller) |
| **Combat** | Do punch, React to character being punched/attacked with melee, Basic list of attacking states, Reacting to damage states, Win, KO, Die, Throw fireball, Fireball moving as a level trap or enemy spell, Change a weapon/model/hat/shield |
| **Emotions & Reactions** | Taunt/dancing/dab state, Basic emotional trigger animations for JRPG cutscenes (angry, happy, excited, loved, scared, sad, depressed), Time over Message from fighting games, Go here message from beatem ups |
| **Interactions** | Create a NPC JRPG like message, Save file, Increase HP, Decrease HP, Change GUI variable, Move and tween camera, Make a character jump, Move a platform between two points, Scene transition, Call a certain sound, music, animation, Play a random music loop from a list, Play cutscene, Enter timer, Open an inventory, Select RTS units using the mouse, Drag an item, Carry an item, Aim like an FPS, Drop loot, Throw a pokeball/item, Give commands to pets/pokemons like a real time action JRPG party, Show a GUI screen, Hide a GUI element, Change a GUI widget, Turn on a flashlight, Turn off, Camera following something, Open a lock/safe, Switch object with a damaged version |
| **Visual Effects** | Make light or sun rotate in the scene, Show a texture on snow footsteps, Damage to model from being shot, or wear and tear, Weather animations like snow, rain, sunny day lenses post processing templates, Particles for fire, lava, explosion, candy/confetti, Bouncing/Mirroring a tennis/pong ball |

**Comment by fire** [comment]
Thanks for your input, but this list is more suitable for a discussion rather than an issue to be fixed on visual script.
