### ISSUE TITLE
Laggy to use Visual-Script in Godot master

### ISSUE THREAD

**Issue by kitsdream** [godotengine/godot-visual-script#57]
### Godot version

Godot 4.0.3 stable

### System information

Windows11

### Issue description

I compiled the code with the latest Visual-Script and Godot 4.0.3 stable. Although the compilation was successful, it is very laggy to use, especially when right-clicking to open the search box in the visual script editing interface. It takes a long time to search for what I want.Will you continue to optimize and update Visual-Script Code until it runs smoothly?

### Steps to reproduce

It is very laggy to use, especially when right-clicking to open the search box in the visual script editing interface. It takes a long time to search for what I want.

**Comment by fire** [comment]
I am trying to fix the visual script pr. It's not ready to merge yet.

**Comment by fire** [comment]
If you can assist, that'll help!

**Comment by kitsdream** [comment]
> 如果你能提供帮助，那会有所帮助！
I will continue to follow your progress updates and actively try to use it, even providing feedback to help you update and optimize it, until it becomes more user-friendly and excellent.

**Comment by fire** [comment]
Let's use this bug report to track the slow search and your pr.

**Comment by kitsdream** [comment]
> @kitsdream If you want, I can consider giving you commit access to this repository.
> 
> Note that Godot Engine has some workflow rules.
> 
> 1. The github actions tests must pass
> 2. We want each pr to be reviewed.
> 3. One commit typically per pr.
> 4. See the pr workflow document.
> 
> https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html

I restore and fix again.Now it just a little bit differences between my changes and your codes.

**Comment by fire** [comment]
Can you make a pull request?

**Comment by kitsdream** [comment]
> Can you make a pull request?

Yes,I did,I make a pr @V-Sekai.

**Comment by kitsdream** [comment]
There is an error here.

 In file included from ./core/templates/cowdata.h:35,
                 from ./core/string/ustring.h:37,
                 from ./core/string/string_name.h:35,
                 from ./core/debugger/engine_debugger.h:34,
                 from modules/visual_script/visual_script.h:34,
                 from modules/visual_script/visual_script.cpp:31:
modules/visual_script/visual_script.cpp: In member function 'virtual ScriptInstance* VisualScript::instance_create(Object*)':
modules/visual_script/visual_script.cpp:846:42: error: invalid new-expression of abstract class type 'VisualScriptInstance'
  846 |  VisualScriptInstance *instance = memnew(VisualScriptInstance);
      |                                          ^~~~~~~~~~~~~~~~~~~~
./core/os/memory.h:94:51: note: in definition of macro 'memnew'
   94 | #define memnew(m_class) _post_initialize(new ("") m_class)
      |                                                   ^~~~~~~
In file included from modules/visual_script/visual_script.cpp:31:
modules/visual_script/visual_script.h:411:7: note:   because the following virtual functions are pure within 'VisualScriptInstance':
  411 | class VisualScriptInstance : public ScriptInstance {
      |       ^~~~~~~~~~~~~~~~~~~~
In file included from ./core/debugger/script_debugger.h:34,
                 from modules/visual_script/visual_script.h:35,
                 from modules/visual_script/visual_script.cpp:31:
./core/object/script_language.h:183:15: note: 	'virtual void ScriptInstance::validate_property(PropertyInfo&) const'
  183 |  virtual void validate_property(PropertyInfo &p_property) const = 0;
      |               ^~~~~~~~~~~~~~~~~
./core/object/script_language.h:208:15: note: 	'virtual void ScriptInstance::notification(int, bool)'
  208 |  virtual void notification(int p_notification, bool p_reversed = false) = 0;
      |               ^~~~~~~~~~~~

**Comment by fire** [comment]
I'll check on this. I pushed a test at https://github.com/V-Sekai/godot/tree/vsk-visual-script. ETA 30minutes-60minutes

**Comment by fire** [comment]
I lost the change, will have to remake it.

**Comment by fire** [comment]
I pushed the changes to the git repository.

**Comment by fire** [comment]
Closing as this has been fixed.
