### ISSUE TITLE
Compilation Error with 4.1.2 RC

### ISSUE THREAD

**Issue by ANGRIO12** [godotengine/godot-visual-script#58]
### Godot version

4.1.2.rc 6884be6 

### System information

Windows 10, GLES2 , i7 6600U, Integrated Graphics HD 520 

### Issue description

![image](https://github.com/godotengine/godot-visual-script/assets/106016342/8a2b0794-d01e-47a7-8ff4-d3a37cebaed3) 
I'm working on my own fork of the godot engine, with visual scripting and some other features, but anytime i compile the engine with the visual scripting code in the "modules" folder, it does this.

### Steps to reproduce

1. Get the Source for 4.1.2 RC on Godot's Repo. 
2. Get the Source for the Visual Script C++ Plugin, also from godot
3. Extract the Source
4. Extract the Visual Script ZIP
5. Rename Visual Script folder to "Visual_Script"
6. Move to modules folder
7. Open CMD and run scons

### Minimal reproduction project
see if it happens when you extract this folder, and run scons 
https://drive.google.com/file/d/14cRr8N9rsAfSimpOtDcVXXS-aJp2XPDf/view?usp=sharing

**Comment by Malkverbena** [comment]
Same issue here.

**Comment by fire** [comment]
I am best effort porting to the latest godot here: https://github.com/godotengine/godot-visual-script/pull/55

**Comment by charlesmlamb** [comment]
this feature is -- very -- important for solo - developers, and also small teams // people that also are trying to learn code at all, and imo the W4 - Foundation should make efforts to give money to work on this feature, or simply hire a small team of programmers, and then get the feature to a ' good enough ' - state . . .

atm, and have moved to a different engine, and the #specific reason is that visual script is missing, and gonna look for updates, or at all news that this feature is towards operational . . .

**Comment by fire** [comment]
I updated the visual script branch onto master. https://github.com/godotengine/godot/commit/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe
