### ISSUE TITLE
Compilation Error with 4.0.4 and 4.1.1

### ISSUE THREAD

**Issue by kitsdream** [godotengine/godot-visual-script#59]
### Godot version

Godot 4.0.4 stable and Godot 4.1.1

### System information

Windows11

### Issue description

When I compiling with lastest Next visual script.it appears:
"D:\Godot\Codes\20230816\godot-4.0.4-stable\godot-4.0.4-stable\modules\visual_script\editor/visual_script_editor.h(38): fatal error C1083: 无法打开包括文件: “scene/resources/style_box_flat.h”: No such file or directory
scons: *** [modules\visual_script\register_types.windows.editor.x86_64.obj] Error 2"

### Steps to reproduce

When I compiling with lastest Next visual script.

### Minimal reproduction project

When I compiling with lastest Next visual script.

**Comment by fire** [comment]
I'll take a look.

**Comment by fire** [comment]
```diff
% git diff
diff --git a/editor/visual_script_property_selector.cpp b/editor/visual_script_property_selector.cpp
index d79b01b..fe2c3d0 100644
--- a/editor/visual_script_property_selector.cpp
+++ b/editor/visual_script_property_selector.cpp
@@ -42,7 +42,7 @@
 #include "editor/editor_node.h"
 #include "editor/editor_scale.h"
 #include "editor/editor_settings.h"
-#include "editor/visual_script_property_selector.h"
+#include "modules/visual_script/editor/visual_script_property_selector.h"
 #include "scene/main/node.h"
 #include "scene/main/window.h"
```

I did this.

**Comment by fire** [comment]
The next branch is based on master which is 4.2. 

I'll post a top commit. https://github.com/godotengine/godot/commit/5444afae63f37cb4b890c781e5679a3b7ee5a392

**Comment by fire** [comment]
Can you check?

**Comment by kitsdream** [comment]
> Can you check?

OK,I'll check it.

**Comment by kitsdream** [comment]
> ```diff
> diff --git a/editor/visual_script_property_selector.cpp b/editor/visual_script_property_selector.cpp
> index d79b01b..fe2c3d0 100644
> --- a/editor/visual_script_property_selector.cpp
> +++ b/editor/visual_script_property_selector.cpp
> @@ -42,7 +42,7 @@
>  #include "editor/editor_node.h"
>  #include "editor/editor_scale.h"
>  #include "editor/editor_settings.h"
> -#include "editor/visual_script_property_selector.h"
> +#include "modules/visual_script/editor/visual_script_property_selector.h"
>  #include "scene/main/node.h"
>  #include "scene/main/window.h"
> ```
> 
> I did this.

I checked it,but still appears this below:

vp8l_dec.c
modules\visual_script\editor\visual_script_property_selector.cpp(45): fatal error C1083: 无法打开包括文件: “editor/visual_script_property_selector.h”: No such file or directory
vp8_dec.c
scons: *** [modules\visual_script\editor\visual_script_property_selector.windows.editor.x86_64.obj] Error 2

**Comment by kitsdream** [comment]
> The next branch is based on master which is 4.2.
> 
> I'll post a top commit. [godotengine/godot@5444afa](https://github.com/godotengine/godot/commit/5444afae63f37cb4b890c781e5679a3b7ee5a392)

I'm compiling with 4.2 dev3,but still have some issues:
vp8l_dec.c
modules\visual_script\editor\visual_script_property_selector.cpp(45): fatal error C1083: 无法打开包括文件: “editor/visual_script_property_selector.h”: No such file or directory
vp8_dec.c
scons: *** [modules\visual_script\editor\visual_script_property_selector.windows.editor.x86_64.obj] Error 2

**Comment by kitsdream** [comment]
> Can you check?

I tried twice and have this:
modules\visual_scrip                                                                                                   pt\editor\visual_script_property_selector.cpp(45): fatal error C1083: 无法打开包括文件: “editor/visual_script_property_selector.h”: No such file or directory
sharpyuv_dsp.c
[Initial build] sharpyuv_sse2.c
sharpyuv_neon.c
[Initial build] sharpyuv_gamma.c
[Initial build] Compiling thirdparty\libwebp\src\dec\alpha_dec.c ...
scons: *** [modules\visual_script\editor\visual_script_property_selector.windows.editor.x86_64.obj] Error 2
alpha_dec.c
modules\visual_script\editor\visual_script_editor.cpp(2214): warning C4458: “data”的声明隐藏了类成员
.\scene/gui/control.h(262): note: 参见“Control::data”的声明
modules\visual_script\editor\visual_script_editor.cpp(4045): warning C4458: “script”的声明隐藏了类成员
D:\Godot\Codes\20230816\godot-4.2-dev3\godot-4.2-dev3\modules\visual_script\editor\visual_script_editor.h(104): note: 参见“VisualScriptEditor::script”的声明

**Comment by kitsdream** [comment]
> Can you check?

I tried it with lastest godot main code but I got this:
io_dec.c
modules\visual_script\editor\visual_script_property_selector.cpp(45): fatal error C1083: 无法打开包括文件: “editor/visual_script_property_selector.h”: No such file or directory
[Initial build] Compiling thirdparty\libwebp\src\dec\quant_dec.c ...
[Initial build] Compiling thirdparty\libwebp\src\dec\tree_dec.c ...
[Initial build] quant_dec.c
Compiling thirdparty\libwebp\src\dec\vp8_dec.c ...
tree_dec.c
vp8_dec.c
[Initial build] scons: *** [modules\visual_script\editor\visual_script_property_selector.windows.editor.x86_64.obj] Error 2
Compiling thirdparty\libwebp\src\dec\vp8l_dec.c ...
vp8l_dec.c
modules\visual_script\editor\visual_script_editor.cpp(2214): warning C4458: “data”的声明隐藏了类成员
.\scene/gui/control.h(262): note: 参见“Control::data”的声明
modules\visual_script\editor\visual_script_editor.cpp(4045): warning C4458: “script”的声明隐藏了类成员
D:\Godot\Codes\20230816\godot-master\godot-master\modules\visual_script\editor\visual_script_editor.h(104): note: 参见“VisualScriptEditor::script”的声明

**Comment by fire** [comment]
I tested `https://github.com/V-Sekai/godot_visual_script.git` @ next branch recently. That's odd.

**Comment by kitsdream** [comment]
> I tested `https://github.com/V-Sekai/godot_visual_script.git` @ next branch recently on master. That's odd.
> 
> It passed cicd. #55

I tried again with lastest main code of 4.2,but still got this:

modules\visual_script\editor\visual_script_property_selector.cpp(45): fatal error C1083: 无法打开包括文件: “editor/visual_script_property_selector.h”: No such file or directory
[Initial build] Compiling thirdparty\libwebp\src\dec\alpha_dec.c ...
scons: *** [modules\visual_script\editor\visual_script_property_selector.windows.editor.x86_64.obj] Error 2
alpha_dec.c
modules\visual_script\editor\visual_script_editor.cpp(2214): warning C4458: “data”的声明隐藏了类成员
.\scene/gui/control.h(262): note: 参见“Control::data”的声明
modules\visual_script\editor\visual_script_editor.cpp(4045): warning C4458: “script”的声明隐藏了类成员
D:\Godot\Codes\20230816\godot-master\godot-master\modules\visual_script\editor\visual_script_editor.h(104): note: 参见“VisualScriptEditor::script”的声明

**Comment by fire** [comment]
what are your git hashes?

**Comment by kitsdream** [comment]
> ```diff
> diff --git a/editor/visual_script_property_selector.cpp b/editor/visual_script_property_selector.cpp
> index d79b01b..fe2c3d0 100644
> --- a/editor/visual_script_property_selector.cpp
> +++ b/editor/visual_script_property_selector.cpp
> @@ -42,7 +42,7 @@
>  #include "editor/editor_node.h"
>  #include "editor/editor_scale.h"
>  #include "editor/editor_settings.h"
> -#include "editor/visual_script_property_selector.h"
> +#include "modules/visual_script/editor/visual_script_property_selector.h"
>  #include "scene/main/node.h"
>  #include "scene/main/window.h"
> ```
> 
> I did this.

Well done!
Haha,I got it that I forgot to make this change,when I change this and compile,It works!!
I realized you had updated the codes,then I re-download it,but forgot to check this line.
Thanks very much,and expecting the updates and new funtions.

**Comment by kitsdream** [comment]
> I tested `https://github.com/V-Sekai/godot_visual_script.git` @ next branch recently on master. That's odd.
> 
> It passed cicd. #55

Now I had compiled it sucessful,and I check it,but I found it,the visual script right click search box still very slow.

**Comment by fire** [comment]
> Now I had compiled it sucessful,and I check it,but I found it,the visual script right click search box still very slow.

Sounds like progress, I'm thinking of merging the next branch to the main repo then.

* Visual script flow nodes are missing.
* Survey ux
* Fix visual script guess nodes to be "self" instead of "instanced".
* Restore visual script native functions.
* Slow lookups

**Comment by kitsdream** [comment]
> > Now I had compiled it sucessful,and I check it,but I found it,the visual script right click search box still very slow.
> 
> Sounds like progress, I'm thinking of merging the next branch to the main repo then.
> 
> ## TODO
> * Visual script flow nodes are missing.
> * Survey ux
> * Fix visual script guess nodes to be "self" instead of "instanced".
> * Restore visual script native functions.
> * Slow lookups

I fixed slow lookups,it is smooth now,but there are some differences in the codes.
Can you check?

**Comment by fire** [comment]
Going to close this issue as the branch now is on top of Godot Engine master. 

Will make an issue for the slow lookups. We can continue there.
